services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    networks:
      - e2ee-net
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    networks:
      - e2ee-net
    depends_on:
      - server

networks:
  e2ee-net:
    driver: bridge